const users = [
  {
    Id_user: 10,
    Pseudo: "Léa",
    Email: "Léa@mannia.fr",
    PassWord: "100",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 11,
    Pseudo: "Sophie",
    Email: "Sophie@mannia.fr",
    PassWord: "111",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 12,
    Pseudo: "Marie",
    Email: "Marie@mannia.fr",
    PassWord: "122",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 13,
    Pseudo: "Lucie",
    Email: "Lucie@mannia.fr",
    PassWord: "133",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 14,
    Pseudo: "Maria2",
    Email: "Maria@mannia.fr",
    PassWord: "144",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 15,
    Pseudo: "Laure",
    Email: "Laure@mannia.fr",
    PassWord: "155",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 16,
    Pseudo: "Anne",
    Email: "Anne@mannia.fr",
    PassWord: "166",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 17,
    Pseudo: "Amy",
    Email: "Amy@mannia.fr",
    PassWord: "177",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
  {
    Id_user: 18,
    Pseudo: "Aurore",
    Email: "Aurore@mannia.fr",
    PassWord: "188",
    Visuel_user: null,
    isAdmin: true,
    isActif: null,
  },
  {
    Id_user: 19,
    Pseudo: "Rose",
    Email: "Rosee@mannia.fr",
    PassWord: "199",
    Visuel_user: null,
    isAdmin: null,
    isActif: null,
  },
];
